# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata_table',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='geodata_table',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
